name: RPM Records Bogota
favicon: null
layout_spectrum: 0.48733
typography_spectrum: 0.25573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#f8e505'
    - '#5e5800'
    - '#c3b71e'
    - '#867415'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
