name: RPM Records Bogota
favicon: null
layout_spectrum: 0.22842
typography_spectrum: 0.20041172695346177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0200'
    - '#f3f1c0'
    - '#d19e05'
    - '#462d02'
    - '#7f7a60'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
