name: RPM Records Bogota
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#feca29'
    - '#ef8901'
    - '#66380b'
    - '#858585'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
