name: RPM Records Bogota
favicon: null
layout_spectrum: 0.46291562588885427
typography_spectrum: 0.2977501682471484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.46521492628380656
  lightness: 0.8175085939001292
  saturation: 0.741018800297752
  rhythmicContrast: 0.6815956085920334
purpose: []
